---

- name: "Incluir variáveis específicas para o SO"
  ansible.builtin.include_vars:
    file: "group_vars/{{ os }}.yaml"
  when: os_type is defined

- name: "get list of files from URL"
  ansible.builtin.uri:
    url: "{{ iso_base_url }}"
    return_content: yes
  register: page_content

- name: "Identify ISO URL to download"
  include_tasks: arch-download.yaml
  when: vm_user == 'arch'

- name: "Identify ISO URL to download"
  include_tasks: ubuntu-download.yaml
  when: vm_user == 'ubuntu'

- name: "Debug Complete URL"
  debug:
    msg: "{{ iso_url }}"

- name: "Check if ISO file exists"
  ansible.builtin.stat:
    path: "{{ iso_directory }}/{{ iso_file }}"
  register: iso_stat

- name: "Donwload ISO file"
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    dest: "{{ iso_directory }}"
  when: not iso_stat.stat.exists

- name: "Create VM on Proxmox"
  include_tasks: proxmox-create-vm.yaml