---
- name: "Check if template VM already exists"
  ansible.builtin.shell: qm list | awk '{print $1}' | grep -x "{{ vm_template_id }}"
  register: vm_exists
  failed_when: false
  changed_when: false

- name: "Create VM"
  ansible.builtin.shell: "{{ cmd }}"
  loop:
    - "qm create {{ vm_template_id }} --name {{ vm_template_name }}"
    - "qm set {{ vm_template_id }} --tags dotfiles"
    - "qm set {{ vm_template_id }} --sockets {{ sockets }} --cores {{ cores }}"
    - "qm set {{ vm_template_id }} --memory {{ memory }}"
    - "qm set {{ vm_template_id }} --net0 virtio,bridge=vmbr0"
    - "qm set {{ vm_template_id }} --scsihw virtio-scsi-pci"
    - "qm set {{ vm_template_id }} --ostype l26"
    - "pvesm alloc {{ vm_storage }} {{ vm_template_id }} vm-{{ vm_template_id }}-disk-0 {{ disk_size }}"
    - "qm set {{ vm_template_id }} --scsi0  {{ vm_storage }}:vm-{{ vm_template_id }}-disk-0"
    - "qm set {{ vm_template_id }} --boot c"
    - "qm set {{ vm_template_id }} --bootdisk ide2"
    - "qm set {{ vm_template_id }} --cdrom {{ iso_storage }}:iso/{{ iso_url | basename }}"
    - "qm set {{ vm_template_id }} --agent enabled=1"
    - "qm set {{ vm_template_id }} --serial0 socket"
    - "qm set {{ vm_template_id }} --vga qxl,memory=125"
  loop_control:
    loop_var: cmd
  when: vm_exists.rc != 0

# Deploy Notes
###############################################################
- name: "Render VM notes template to /tmp"
  ansible.builtin.template:
    src: notes.md.j2
    dest: "/tmp/notes_creation.md"

- name: "Apply notes to VM description"
  ansible.builtin.shell: |
    qm set {{ vm_template_id }} --description "$(cat /tmp/notes_creation.md)"

- name: "Remove temporary VM notes file"
  ansible.builtin.file:
    path: "/tmp/notes_creation.md"
    state: absent
