---

- name: "Load OS-specific variables"
  ansible.builtin.include_vars:
    file: "group_vars/{{ os }}.yaml"
  when: os_type is defined

- name: "Check if VM already exists"
  ansible.builtin.shell: qm list | awk '{print $1}' | grep -x "{{ vm_id }}"
  register: vm_exists
  failed_when: false
  changed_when: false

- name: "Check if VM is running"
  ansible.builtin.shell: |
    qm status {{ vm_id }} | grep -q "status: running"
  register: vm_running
  failed_when: false
  changed_when: false
  when: vm_exists.rc == 0

- name: "Start VM if it is not running"
  ansible.builtin.shell: |
    qm start {{ vm_id }}
  when: vm_exists.rc == 0 and vm_running.rc != 0
  register: start_vm_result
  changed_when: true
  failed_when: start_vm_result.rc != 0

- name: "Wait for VM to be running"
  ansible.builtin.shell: |
    qm status {{ vm_id }} | grep -q "status: running"
  register: vm_start_wait
  until: vm_start_wait.rc == 0
  retries: 30
  delay: 5
  changed_when: false
  when: vm_exists.rc == 0 and vm_running.rc != 0
