---

- name: "Incluir variáveis específicas para o SO"
  ansible.builtin.include_vars:
    file: "group_vars/{{ os }}.yaml"
  when: os_type is defined

- name: "Check if VM already exist"
  ansible.builtin.shell: qm list | grep -q "{{ vm_id }}"
  register: vm_exists
  failed_when: "vm_exists.rc == 1 and 'non-zero return code' in vm_exists.stderr"
  ignore_errors: yes

- name: "Check if VM is running"
  ansible.builtin.shell: |
    qm status {{ vm_id }} | grep -q "status: running"
  register: vm_running
  failed_when: false
  changed_when: false
  when: vm_exists.rc == 0

- name: "Start VM if it is running"
  ansible.builtin.shell: |
    qm start {{ vm_id }}
  when: vm_running.rc != 0
  register: start_vm_result
  changed_when: vm_running.rc == 0
  failed_when: start_vm_result.rc != 0