name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'

jobs:

  Publish-Image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract tag
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ env.TAG }}" \
            --repo="${{ github.repository }}" \
            --title="Release ${{ env.TAG }}" \
            --generate-notes

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}
